# Generated by Django 6.0 on 2026-01-09 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='العنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط')),
                ('excerpt', models.TextField(verbose_name='الملخص')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('featured_image', models.URLField(blank=True, max_length=1000, null=True, verbose_name='الصورة المميزة')),
                ('is_breaking', models.BooleanField(default=False, verbose_name='خبر عاجل')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('views', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('likes', models.IntegerField(default=0, verbose_name='عدد الإعجابات')),
                ('comments', models.IntegerField(default=0, verbose_name='عدد التعليقات')),
                ('reading_time', models.IntegerField(default=1, verbose_name='وقت القراءة (دقائق)')),
                ('published_at', models.DateTimeField(verbose_name='تاريخ النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'مقالات',
                'db_table': 'news_article',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('avatar', models.URLField(max_length=500, verbose_name='الصورة')),
                ('bio', models.TextField(verbose_name='السيرة الذاتية')),
                ('role', models.CharField(default='reporter', max_length=50, verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'مؤلف',
                'verbose_name_plural': 'مؤلفين',
                'db_table': 'news_author',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط')),
                ('color', models.CharField(default='#3B82F6', max_length=20, verbose_name='اللون')),
                ('icon', models.CharField(default='category', max_length=50, verbose_name='الرمز')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'تصنيفات',
                'db_table': 'news_category',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='نوع الحدث')),
                ('data', models.JSONField(verbose_name='البيانات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التوقيت')),
            ],
            options={
                'verbose_name': 'حدث',
                'verbose_name_plural': 'أحداث',
                'db_table': 'news_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الوسم')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط')),
            ],
            options={
                'verbose_name': 'وسم',
                'verbose_name_plural': 'وسوم',
                'db_table': 'news_tag',
            },
        ),
        migrations.DeleteModel(
            name='ArticleModle',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.author', verbose_name='المؤلف'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category', verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='news.tag', verbose_name='الوسوم'),
        ),
    ]
