# Generated by Django 4.2.30 on 2026-08-02 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news_article_like',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='الإجراء')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='البيانات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التوقيت')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'db_table': 'news_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'مقال', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='وصف SEO'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='article',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text="اترك فارغاً للنشر الفوري عند تغيير الحالة إلى 'منشور'", null=True, verbose_name='موعد النشر المجدول'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('pending_review', 'قيد المراجعة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='حالة النشر'),
        ),
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد التعليقات'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الإعجابات'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reading_time',
            field=models.PositiveIntegerField(default=1, verbose_name='وقت القراءة (دقائق)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=500, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='news_articl_status_f1b279_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_breaking'], name='news_articl_is_brea_cfd84b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured'], name='news_articl_is_feat_0df2de_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-created_at'], name='news_articl_created_a034b3_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='articlelike',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_records', to='news.article'),
        ),
        migrations.AddField(
            model_name='articlelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='articlelike',
            unique_together={('article', 'user')},
        ),
    ]
