# Generated by Django 4.2.30 on 2026-08-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_editor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_reporter',
        ),
    ]
